name: telemetry_sh
description: A simple telemetry logging SDK for Dart
version: 1.0.0
repository: https://github.com/Rohithgilla12
topics: [dart, telemetry, logging, sdk]
homepage: https://docs.telemetry.sh/

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
dependencies:
  http: ^1.2.2
